# Generated by Django 6.0 on 2025-12-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complted',
            new_name='completed',
        ),
    ]
